version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/spring_boot_base_project
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Aa@123456
    depends_on:
      - redis
      - postgres
    networks:
      - gateway

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - gateway

  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: spring_boot_base_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa@123456
    ports:
      - "5432:5432"
    networks:
      - gateway
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - gateway

networks:
  gateway:
    driver: bridge
    name: gateway

volumes:
  postgres-data: