version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/spring_boot_base_project
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Aa@123456
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: spring_boot_base_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa@123456
    ports:
      - "5432:5432"